package com.qyxy.domain;

import java.util.Date;

public class Feedback {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FEEDBACK.FEEDBACKID
     *
     * @mbggenerated
     */
    private Short feedbackid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FEEDBACK.FEEDBACKUSERPHONE
     *
     * @mbggenerated
     */
    private String feedbackuserphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FEEDBACK.FEEDBACKCONTENT
     *
     * @mbggenerated
     */
    private String feedbackcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FEEDBACK.FEEDBACKTIME
     *
     * @mbggenerated
     */
    private Date feedbacktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FEEDBACK.FEEDBACKSTATUS
     *
     * @mbggenerated
     */
    private Short feedbackstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FEEDBACK.FEEDBACKID
     *
     * @return the value of FEEDBACK.FEEDBACKID
     *
     * @mbggenerated
     */
    public Short getFeedbackid() {
        return feedbackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FEEDBACK.FEEDBACKID
     *
     * @param feedbackid the value for FEEDBACK.FEEDBACKID
     *
     * @mbggenerated
     */
    public void setFeedbackid(Short feedbackid) {
        this.feedbackid = feedbackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FEEDBACK.FEEDBACKUSERPHONE
     *
     * @return the value of FEEDBACK.FEEDBACKUSERPHONE
     *
     * @mbggenerated
     */
    public String getFeedbackuserphone() {
        return feedbackuserphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FEEDBACK.FEEDBACKUSERPHONE
     *
     * @param feedbackuserphone the value for FEEDBACK.FEEDBACKUSERPHONE
     *
     * @mbggenerated
     */
    public void setFeedbackuserphone(String feedbackuserphone) {
        this.feedbackuserphone = feedbackuserphone == null ? null : feedbackuserphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FEEDBACK.FEEDBACKCONTENT
     *
     * @return the value of FEEDBACK.FEEDBACKCONTENT
     *
     * @mbggenerated
     */
    public String getFeedbackcontent() {
        return feedbackcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FEEDBACK.FEEDBACKCONTENT
     *
     * @param feedbackcontent the value for FEEDBACK.FEEDBACKCONTENT
     *
     * @mbggenerated
     */
    public void setFeedbackcontent(String feedbackcontent) {
        this.feedbackcontent = feedbackcontent == null ? null : feedbackcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FEEDBACK.FEEDBACKTIME
     *
     * @return the value of FEEDBACK.FEEDBACKTIME
     *
     * @mbggenerated
     */
    public Date getFeedbacktime() {
        return feedbacktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FEEDBACK.FEEDBACKTIME
     *
     * @param feedbacktime the value for FEEDBACK.FEEDBACKTIME
     *
     * @mbggenerated
     */
    public void setFeedbacktime(Date feedbacktime) {
        this.feedbacktime = feedbacktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FEEDBACK.FEEDBACKSTATUS
     *
     * @return the value of FEEDBACK.FEEDBACKSTATUS
     *
     * @mbggenerated
     */
    public Short getFeedbackstatus() {
        return feedbackstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FEEDBACK.FEEDBACKSTATUS
     *
     * @param feedbackstatus the value for FEEDBACK.FEEDBACKSTATUS
     *
     * @mbggenerated
     */
    public void setFeedbackstatus(Short feedbackstatus) {
        this.feedbackstatus = feedbackstatus;
    }
}