package com.qyxy.domain;

import java.util.Date;

public class Topic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOPIC.TOPICID
     *
     * @mbggenerated
     */
    private Short topicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOPIC.TOPICTITLE
     *
     * @mbggenerated
     */
    private String topictitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOPIC.READNUMBER
     *
     * @mbggenerated
     */
    private Short readnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOPIC.CLICKNUMBER
     *
     * @mbggenerated
     */
    private Short clicknumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOPIC.COMMENTNUM
     *
     * @mbggenerated
     */
    private Short commentnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOPIC.COMMITTIME
     *
     * @mbggenerated
     */
    private Date committime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOPIC.TOPICRECOM
     *
     * @mbggenerated
     */
    private Short topicrecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOPIC.TOPICSTATU
     *
     * @mbggenerated
     */
    private Short topicstatu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOPIC.TOPICCONTENT
     *
     * @mbggenerated
     */
    private String topiccontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOPIC.TOPICID
     *
     * @return the value of TOPIC.TOPICID
     *
     * @mbggenerated
     */
    public Short getTopicid() {
        return topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOPIC.TOPICID
     *
     * @param topicid the value for TOPIC.TOPICID
     *
     * @mbggenerated
     */
    public void setTopicid(Short topicid) {
        this.topicid = topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOPIC.TOPICTITLE
     *
     * @return the value of TOPIC.TOPICTITLE
     *
     * @mbggenerated
     */
    public String getTopictitle() {
        return topictitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOPIC.TOPICTITLE
     *
     * @param topictitle the value for TOPIC.TOPICTITLE
     *
     * @mbggenerated
     */
    public void setTopictitle(String topictitle) {
        this.topictitle = topictitle == null ? null : topictitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOPIC.READNUMBER
     *
     * @return the value of TOPIC.READNUMBER
     *
     * @mbggenerated
     */
    public Short getReadnumber() {
        return readnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOPIC.READNUMBER
     *
     * @param readnumber the value for TOPIC.READNUMBER
     *
     * @mbggenerated
     */
    public void setReadnumber(Short readnumber) {
        this.readnumber = readnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOPIC.CLICKNUMBER
     *
     * @return the value of TOPIC.CLICKNUMBER
     *
     * @mbggenerated
     */
    public Short getClicknumber() {
        return clicknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOPIC.CLICKNUMBER
     *
     * @param clicknumber the value for TOPIC.CLICKNUMBER
     *
     * @mbggenerated
     */
    public void setClicknumber(Short clicknumber) {
        this.clicknumber = clicknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOPIC.COMMENTNUM
     *
     * @return the value of TOPIC.COMMENTNUM
     *
     * @mbggenerated
     */
    public Short getCommentnum() {
        return commentnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOPIC.COMMENTNUM
     *
     * @param commentnum the value for TOPIC.COMMENTNUM
     *
     * @mbggenerated
     */
    public void setCommentnum(Short commentnum) {
        this.commentnum = commentnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOPIC.COMMITTIME
     *
     * @return the value of TOPIC.COMMITTIME
     *
     * @mbggenerated
     */
    public Date getCommittime() {
        return committime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOPIC.COMMITTIME
     *
     * @param committime the value for TOPIC.COMMITTIME
     *
     * @mbggenerated
     */
    public void setCommittime(Date committime) {
        this.committime = committime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOPIC.TOPICRECOM
     *
     * @return the value of TOPIC.TOPICRECOM
     *
     * @mbggenerated
     */
    public Short getTopicrecom() {
        return topicrecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOPIC.TOPICRECOM
     *
     * @param topicrecom the value for TOPIC.TOPICRECOM
     *
     * @mbggenerated
     */
    public void setTopicrecom(Short topicrecom) {
        this.topicrecom = topicrecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOPIC.TOPICSTATU
     *
     * @return the value of TOPIC.TOPICSTATU
     *
     * @mbggenerated
     */
    public Short getTopicstatu() {
        return topicstatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOPIC.TOPICSTATU
     *
     * @param topicstatu the value for TOPIC.TOPICSTATU
     *
     * @mbggenerated
     */
    public void setTopicstatu(Short topicstatu) {
        this.topicstatu = topicstatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOPIC.TOPICCONTENT
     *
     * @return the value of TOPIC.TOPICCONTENT
     *
     * @mbggenerated
     */
    public String getTopiccontent() {
        return topiccontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOPIC.TOPICCONTENT
     *
     * @param topiccontent the value for TOPIC.TOPICCONTENT
     *
     * @mbggenerated
     */
    public void setTopiccontent(String topiccontent) {
        this.topiccontent = topiccontent == null ? null : topiccontent.trim();
    }
}