package com.qyxy.domain;

public class Upermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UPERMISSION.UPERMISSIONID
     *
     * @mbggenerated
     */
    private Short upermissionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UPERMISSION.UPERMISSIONNAME
     *
     * @mbggenerated
     */
    private String upermissionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UPERMISSION.UPERMISSIONTYPE
     *
     * @mbggenerated
     */
    private String upermissiontype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UPERMISSION.UPERMISSIONURL
     *
     * @mbggenerated
     */
    private String upermissionurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UPERMISSION.PERCODE
     *
     * @mbggenerated
     */
    private String percode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UPERMISSION.PARENTID
     *
     * @mbggenerated
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UPERMISSION.UPERMISSIONSTATUS
     *
     * @mbggenerated
     */
    private Short upermissionstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UPERMISSION.UPERMISSIONID
     *
     * @return the value of UPERMISSION.UPERMISSIONID
     *
     * @mbggenerated
     */
    public Short getUpermissionid() {
        return upermissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UPERMISSION.UPERMISSIONID
     *
     * @param upermissionid the value for UPERMISSION.UPERMISSIONID
     *
     * @mbggenerated
     */
    public void setUpermissionid(Short upermissionid) {
        this.upermissionid = upermissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UPERMISSION.UPERMISSIONNAME
     *
     * @return the value of UPERMISSION.UPERMISSIONNAME
     *
     * @mbggenerated
     */
    public String getUpermissionname() {
        return upermissionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UPERMISSION.UPERMISSIONNAME
     *
     * @param upermissionname the value for UPERMISSION.UPERMISSIONNAME
     *
     * @mbggenerated
     */
    public void setUpermissionname(String upermissionname) {
        this.upermissionname = upermissionname == null ? null : upermissionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UPERMISSION.UPERMISSIONTYPE
     *
     * @return the value of UPERMISSION.UPERMISSIONTYPE
     *
     * @mbggenerated
     */
    public String getUpermissiontype() {
        return upermissiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UPERMISSION.UPERMISSIONTYPE
     *
     * @param upermissiontype the value for UPERMISSION.UPERMISSIONTYPE
     *
     * @mbggenerated
     */
    public void setUpermissiontype(String upermissiontype) {
        this.upermissiontype = upermissiontype == null ? null : upermissiontype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UPERMISSION.UPERMISSIONURL
     *
     * @return the value of UPERMISSION.UPERMISSIONURL
     *
     * @mbggenerated
     */
    public String getUpermissionurl() {
        return upermissionurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UPERMISSION.UPERMISSIONURL
     *
     * @param upermissionurl the value for UPERMISSION.UPERMISSIONURL
     *
     * @mbggenerated
     */
    public void setUpermissionurl(String upermissionurl) {
        this.upermissionurl = upermissionurl == null ? null : upermissionurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UPERMISSION.PERCODE
     *
     * @return the value of UPERMISSION.PERCODE
     *
     * @mbggenerated
     */
    public String getPercode() {
        return percode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UPERMISSION.PERCODE
     *
     * @param percode the value for UPERMISSION.PERCODE
     *
     * @mbggenerated
     */
    public void setPercode(String percode) {
        this.percode = percode == null ? null : percode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UPERMISSION.PARENTID
     *
     * @return the value of UPERMISSION.PARENTID
     *
     * @mbggenerated
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UPERMISSION.PARENTID
     *
     * @param parentid the value for UPERMISSION.PARENTID
     *
     * @mbggenerated
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UPERMISSION.UPERMISSIONSTATUS
     *
     * @return the value of UPERMISSION.UPERMISSIONSTATUS
     *
     * @mbggenerated
     */
    public Short getUpermissionstatus() {
        return upermissionstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UPERMISSION.UPERMISSIONSTATUS
     *
     * @param upermissionstatus the value for UPERMISSION.UPERMISSIONSTATUS
     *
     * @mbggenerated
     */
    public void setUpermissionstatus(Short upermissionstatus) {
        this.upermissionstatus = upermissionstatus;
    }
}