package com.qyxy.domain;

public class Urole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UROLE.UROLEID
     *
     * @mbggenerated
     */
    private Short uroleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UROLE.UROLENAME
     *
     * @mbggenerated
     */
    private String urolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UROLE.UROLESTATUS
     *
     * @mbggenerated
     */
    private Short urolestatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UROLE.UROLEID
     *
     * @return the value of UROLE.UROLEID
     *
     * @mbggenerated
     */
    public Short getUroleid() {
        return uroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UROLE.UROLEID
     *
     * @param uroleid the value for UROLE.UROLEID
     *
     * @mbggenerated
     */
    public void setUroleid(Short uroleid) {
        this.uroleid = uroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UROLE.UROLENAME
     *
     * @return the value of UROLE.UROLENAME
     *
     * @mbggenerated
     */
    public String getUrolename() {
        return urolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UROLE.UROLENAME
     *
     * @param urolename the value for UROLE.UROLENAME
     *
     * @mbggenerated
     */
    public void setUrolename(String urolename) {
        this.urolename = urolename == null ? null : urolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UROLE.UROLESTATUS
     *
     * @return the value of UROLE.UROLESTATUS
     *
     * @mbggenerated
     */
    public Short getUrolestatus() {
        return urolestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UROLE.UROLESTATUS
     *
     * @param urolestatus the value for UROLE.UROLESTATUS
     *
     * @mbggenerated
     */
    public void setUrolestatus(Short urolestatus) {
        this.urolestatus = urolestatus;
    }
}