package com.qyxy.domain;

public class UrolePermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UROLE_PERMISSION.UROLEPERMISSIONID
     *
     * @mbggenerated
     */
    private Short urolepermissionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UROLE_PERMISSION.UROLEID
     *
     * @mbggenerated
     */
    private Short uroleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UROLE_PERMISSION.UPERMISSIONID
     *
     * @mbggenerated
     */
    private Short upermissionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UROLE_PERMISSION.UROLEPERMISSIONID
     *
     * @return the value of UROLE_PERMISSION.UROLEPERMISSIONID
     *
     * @mbggenerated
     */
    public Short getUrolepermissionid() {
        return urolepermissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UROLE_PERMISSION.UROLEPERMISSIONID
     *
     * @param urolepermissionid the value for UROLE_PERMISSION.UROLEPERMISSIONID
     *
     * @mbggenerated
     */
    public void setUrolepermissionid(Short urolepermissionid) {
        this.urolepermissionid = urolepermissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UROLE_PERMISSION.UROLEID
     *
     * @return the value of UROLE_PERMISSION.UROLEID
     *
     * @mbggenerated
     */
    public Short getUroleid() {
        return uroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UROLE_PERMISSION.UROLEID
     *
     * @param uroleid the value for UROLE_PERMISSION.UROLEID
     *
     * @mbggenerated
     */
    public void setUroleid(Short uroleid) {
        this.uroleid = uroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UROLE_PERMISSION.UPERMISSIONID
     *
     * @return the value of UROLE_PERMISSION.UPERMISSIONID
     *
     * @mbggenerated
     */
    public Short getUpermissionid() {
        return upermissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UROLE_PERMISSION.UPERMISSIONID
     *
     * @param upermissionid the value for UROLE_PERMISSION.UPERMISSIONID
     *
     * @mbggenerated
     */
    public void setUpermissionid(Short upermissionid) {
        this.upermissionid = upermissionid;
    }
}