package com.qyxy.domain;

import java.util.Date;
import java.util.List;

public class User1 {
    private Integer userid;
    private String userphone;
    private String userpassword;
    private String nickname;
    private String usericon;
    private String usersex;
    private String useraddress;
    private Date userbirthday;
    private String userstar;
    private String usersingnature;
    private String usersalt;
    private Integer userstatus;//删除状态0代表删除，1代表普通用户，2代表站长
    private Integer userdisable;//禁用状态0代表禁用
    private String constellation;//星座


    public Integer getUserid() {
        return userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public String getUserphone() {
        return userphone;
    }


    public void setUserphone(String userphone) {
        this.userphone = userphone == null ? null : userphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER1.USERPASSWORD
     *
     * @return the value of USER1.USERPASSWORD
     *
     * @mbggenerated
     */
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER1.USERPASSWORD
     *
     * @param userpassword the value for USER1.USERPASSWORD
     *
     * @mbggenerated
     */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword == null ? null : userpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER1.NICKNAME
     *
     * @return the value of USER1.NICKNAME
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER1.NICKNAME
     *
     * @param nickname the value for USER1.NICKNAME
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER1.USERICON
     *
     * @return the value of USER1.USERICON
     *
     * @mbggenerated
     */
    public String getUsericon() {
        return usericon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER1.USERICON
     *
     * @param usericon the value for USER1.USERICON
     *
     * @mbggenerated
     */
    public void setUsericon(String usericon) {
        this.usericon = usericon == null ? null : usericon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER1.USERSEX
     *
     * @return the value of USER1.USERSEX
     *
     * @mbggenerated
     */
    public String  getUsersex() {
        return usersex;
    }


    public void setUsersex(String usersex) {
        this.usersex = usersex;
    }


    public String getUseraddress() {
        return useraddress;
    }


    public void setUseraddress(String useraddress) {
        this.useraddress = useraddress == null ? null : useraddress.trim();
    }


    public Date getUserbirthday() {
        return userbirthday;
    }


    public void setUserbirthday(Date userbirthday) {
        this.userbirthday = userbirthday;
    }


    public String getUserstar() {
        return userstar;
    }

    public void setUserstar(String userstar) {
        this.userstar = userstar == null ? null : userstar.trim();
    }


    public String getUsersingnature() {
        return usersingnature;
    }


    public void setUsersingnature(String usersingnature) {
        this.usersingnature = usersingnature == null ? null : usersingnature.trim();
    }


    public String getUsersalt() {
        return usersalt;
    }


    public void setUsersalt(String usersalt) {
        this.usersalt = usersalt == null ? null : usersalt.trim();
    }


    public Integer getUserstatus() {
        return userstatus;
    }


    public void setUserstatus(Integer userstatus) {
        this.userstatus = userstatus;
    }

    public Integer getUserdisable() {
        return userdisable;
    }

    public void setUserdisable(Integer userdisable) {
        this.userdisable = userdisable;
    }

    public String getConstellation() {
        return constellation;
    }

    public void setConstellation(String constellation) {
        this.constellation = constellation;
    }
}