package com.qyxy.domain;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE.USREROLEID
     *
     * @mbggenerated
     */
    private Short usreroleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE.USERID
     *
     * @mbggenerated
     */
    private Short userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE.UROLEID
     *
     * @mbggenerated
     */
    private Short uroleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE.USREROLEID
     *
     * @return the value of USER_ROLE.USREROLEID
     *
     * @mbggenerated
     */
    public Short getUsreroleid() {
        return usreroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE.USREROLEID
     *
     * @param usreroleid the value for USER_ROLE.USREROLEID
     *
     * @mbggenerated
     */
    public void setUsreroleid(Short usreroleid) {
        this.usreroleid = usreroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE.USERID
     *
     * @return the value of USER_ROLE.USERID
     *
     * @mbggenerated
     */
    public Short getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE.USERID
     *
     * @param userid the value for USER_ROLE.USERID
     *
     * @mbggenerated
     */
    public void setUserid(Short userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE.UROLEID
     *
     * @return the value of USER_ROLE.UROLEID
     *
     * @mbggenerated
     */
    public Short getUroleid() {
        return uroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE.UROLEID
     *
     * @param uroleid the value for USER_ROLE.UROLEID
     *
     * @mbggenerated
     */
    public void setUroleid(Short uroleid) {
        this.uroleid = uroleid;
    }
}